### ISSUE TITLE
Antlr4 Version

### ISSUE THREAD

**Issue by rgoulter** [melix/antlr4-gradle-plugin#8]
This gradle plugin makes use of Antlr 4.2.  

This gives a bit of grief if using newer versions of Antlr 4 generated outside of gradle & this plugin. e.g. `RuntimeMetaData` introduced in 4.3 is problematic. If I use gradle to generate Eclipse sources, and then use an Antlr4 Eclipse plugin (https://github.com/jknack/antlr4ide) to invoke Antlr (v4.4), it can't compile the Java (since the project classpath refers to Antlr v4.2 as per gradle & this plugin).  

I _could_ downgrade entirely to Antlr 4.2, or I _could_ set the Eclipse Antlr plugin to use 4.2 for any/all projects generated using this plugin. But I'd rather wish there were a way for this plugin to use a different/particular version of Antlr4.

**Comment by klimeryk** [comment]
You can override the antlr4's version by explicitly setting the dependency on the `antlr4` configuration:

    dependencies {
        antlr4 'org.antlr:antlr4:4.5'
    }

You can verify this with the `dependencies` task.

**Comment by rgoulter** [comment]
Ah, clearly I wasn't aware of how to do this. :-) Thanks for clarifying.
